kind: pipeline
name: terraform-google-astronomer-cloud

steps:

- name: lint
  image: hashicorp/terraform:light
  commands:
    - cp providers.tf.example providers.tf
    - terraform init
    - terraform fmt -check=true
    - terraform validate
    - rm -rf .terraform
    - terraform -v
  when:
    event:
      - pull_request
      - push
